#This is the frontend CI/CD Pipeline for pushing to the project to CSC Openshift platform
image: ayufan/openshift-cli

stages:
    - preparation
    - testing
    - build

variables:
  OPENSHIFT_SERVER: https://rahti.csc.fi:8443/
  OPENSHIFT_DOMAIN: rahti.csc.fi
  
# Before script is executed before every job
.deploy: &deploy
  before_script:
    - cd
  tags:
    - shell
    
GitClone:
  stage: preparation
  script:
  - cd /home/gitlab-runner/builds/s2mU8de_/0/digiateam/front-end/
  #- git clone https://gitlab.labranet.jamk.fi/digiateam/backend.git

# $OPENSHIFT_TOKEN specified in proj settings CI/CD Variables, make sure it's protected
login:
  stage: preparation
  script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc status
    - oc whoami
    - echo $CI_PROJECT_NAME

Eslint:
  stage: testing
  allow_failure: true
  script:
    - npm install eslint --save-dev
    - npm install eslint-plugin-react@latest --save-dev
    - ./node_modules/.bin/eslint src/**

BuildProductionToOpenshift_Manual:
 stage: build
 when: manual
 script:
    - unset CI
    - npm ci # Build for prod
    - REACT_APP_API_URL=http://backend-tuhlari.rahtiapp.fi/ npm run build --prod
    - oc project tuhlari
    - oc start-build front-end --from-dir="build" --follow --wait
