# This file is a template, and might need editing before it works on your project. testcomment
image: ayufan/openshift-cli

stages:
    - testing
    - build

variables:
  OPENSHIFT_SERVER: https://rahti.csc.fi:8443/
  OPENSHIFT_DOMAIN: rahti.csc.fi
  
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: "$OPENSHIFT_TOKEN"

.deploy: &deploy
  before_script:
    - cd
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc status
    - oc whoami
    - echo $CI_PROJECT_NAME
    - git clone https://gitlab.labranet.jamk.fi/digiateam/front-end.git
  tags:
    - shell

image: node

eslint:
  stage: testing
  allow_failure: true
  script:
    - npm install eslint --save-dev
    - npm install eslint-plugin-react --save-dev
    - ./node_modules/.bin/eslint --ext .js --env browser --plugin react src/**
    #- echo '1\r 1\r N\r a\r 3\r Y\r' | ./node_modules/.bin/eslint --init
    #- ./node_modules/.bin/eslint src/**
  
dependency_scanning:
  stage: testing
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - echo $SP_VERSION
    - docker run
        --dns 8.8.8.8
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths:
    reports:
      dependency_scanning: $CI_PROJECT_DIR/gl-dependency-scanning-report.json
    expire_in: 1 week
  allow_failure: true
  tags:
    - general

# This file is a template, and might need editing before it works on your project.
code_quality:
  stage: testing
  image: docker:stable
  allow_failure: true
  services:
    - docker:stable-dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    CODE_QUALITY_IMAGE: "registry.gitlab.com/gitlab-org/security-products/codequality:0.85.6"
  script:
    - |
      if ! docker info &>/dev/null; then
        if [ -z "$DOCKER_HOST" -a "$KUBERNETES_PORT" ]; then
          export DOCKER_HOST='tcp://localhost:2375'
        fi
      fi
    - docker pull registry.gitlab.com/gitlab-org/security-products/codequality:0.85.6
    - docker run 
        --dns 8.8.8.8
        --env SOURCE_CODE="$PWD"
        --volume "$PWD":/code
        --volume /var/run/docker.sock:/var/run/docker.sock
        "$CODE_QUALITY_IMAGE" /code
  artifacts:
    reports:
      codequality: $CI_PROJECT_DIR/gl-code-quality-report.json
    expire_in: 1 week
  dependencies: []
  only:
    refs:
      - branches
      - tags
  except:
    variables:
      - $CODE_QUALITY_DISABLED
  tags:
    - shell



buildProductToOpenshift:
 stage: build
 script:
    - ls
    - unset CI
    - npm ci # Build for prod
    - REACT_APP_API_URL=http://backend-tuhlari.rahtiapp.fi/ npm run build --prod
    - oc project tuhlari
    - oc start-build front-end --from-dir="build" --follow --wait