# This file is a template, and might need editing before it works on your project. testcomment
image: ayufan/openshift-cli

stages:

variables:
  OPENSHIFT_SERVER: https://rahti.csc.fi:8443/
  OPENSHIFT_DOMAIN: rahti.csc.fi
  
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: "$OPENSHIFT_TOKEN"

.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc status
    - oc whoami
    - echo $CI_PROJECT_NAME
  tags:
    - shell

steps:
# Install Node.js
- task: NodeTool@0
  inputs:
    versionSpec: $(nodeVersion)
  displayName: 'Install Node.js'

# Install node modules.
- script: |
    npm install
  displayName: 'NPM Install'

# Uses NPM to run the `lint` script that I included in my package.json
- task: Npm@1
  inputs:
    command: custom
    customCommand: 'run lint'
  displayName: Run ESLint
  # Uncomment the following line if you *don't* want the pipeline to fail when ESLint fails.
  #continueOnError: true 

# Runs the `test` script that I included in my package.json
- task: Npm@1
  inputs:
    command: custom
    customCommand: 'test'
  displayName: Run Tests

buildProductToOpenshift:
 script:
    - git clone https://gitlab.labranet.jamk.fi/digiateam/front-end.git
    - cd front-end
    - unset CI
    - npm ci # Build for prod
    - REACT_APP_API_URL=http://backend-tuhlari.rahtiapp.fi/ npm run build --prod
    - oc project tuhlari
    - oc start-build front-end --from-dir="build" --follow --wait