# This file is a template, and might need editing before it works on your project. testcomment
image: ayufan/openshift-cli

stages:

variables:
  OPENSHIFT_SERVER: https://rahti.csc.fi:8443/
  OPENSHIFT_DOMAIN: rahti.csc.fi
  
  # Configure this variable in Secure Variables:
  OPENSHIFT_TOKEN: "$OPENSHIFT_TOKEN"

.deploy: &deploy
  before_script:
    - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
    - oc status
    - oc whoami
    - echo $CI_PROJECT_NAME
    - git clone https://gitlab.labranet.jamk.fi/digiateam/front-end.git
  tags:
    - shell

ESLint:
 script:
    - npm install -g eslint
    - npm install -g eslint-plugin-react
    - eslint --init
    - eslint front-end
    #- continueOnError: true


buildProductToOpenshift:
 script:
    - cd front-end
    - unset CI
    - npm ci # Build for prod
    - REACT_APP_API_URL=http://backend-tuhlari.rahtiapp.fi/ npm run build --prod
    - oc project tuhlari
    - oc start-build front-end --from-dir="build" --follow --wait